import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form FastCash
     */
    public FastCash() {
        initComponents();
    }
    int MyAccNum;
    public FastCash(int AccNum) {
        initComponents();
        MyAccNum=AccNum;
        setBalance();
    }
    private void setBalance(){

        String q = "SELECT * FROM ACCOUNTTABLE WHERE AccNum = '"+MyAccNum+"'";
        try{
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
            Statement st = con.createStatement();
            ResultSet rs1 =st.executeQuery(q);
            if(rs1.next()){
                int b = rs1.getInt(9);
                BalanceTb.setText(""+b);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }


    }
    private int getBalance(){

        String q = "SELECT * FROM ACCOUNTTABLE WHERE AccNum = '"+MyAccNum+"'";
        try{
            Class.forName("java.sql.DriverManager");
            java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
            Statement st = con.createStatement();
            ResultSet rs1 =st.executeQuery(q);
            if(rs1.next()){
                int b = rs1.getInt(9);
                return b;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        return 0;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rs100Btn = new javax.swing.JButton();
        Rs200Btn = new javax.swing.JButton();
        Rs500Btn = new javax.swing.JButton();
        Rs1000Btn = new javax.swing.JButton();
        Rs5000Btn = new javax.swing.JButton();
        Rs10000Btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BalanceTb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAK Bank");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)
                                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("FAST CASH");

        Rs100Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rs100Btn.setForeground(new java.awt.Color(0, 51, 255));
        Rs100Btn.setText("RS 100");
        Rs100Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rs100BtnMouseClicked(evt);
            }
        });
        Rs100Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rs100BtnActionPerformed(evt);
            }
        });

        Rs200Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rs200Btn.setForeground(new java.awt.Color(0, 51, 255));
        Rs200Btn.setText("RS 200");
        Rs200Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rs200BtnMouseClicked(evt);
            }
        });
        Rs200Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rs200BtnActionPerformed(evt);
            }
        });

        Rs500Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rs500Btn.setForeground(new java.awt.Color(0, 51, 255));
        Rs500Btn.setText("RS 500");
        Rs500Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rs500BtnMouseClicked(evt);
            }
        });
        Rs500Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rs500BtnActionPerformed(evt);
            }
        });

        Rs1000Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rs1000Btn.setForeground(new java.awt.Color(0, 51, 255));
        Rs1000Btn.setText("RS 1000");
        Rs1000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rs1000BtnMouseClicked(evt);
            }
        });

        Rs5000Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rs5000Btn.setForeground(new java.awt.Color(0, 51, 255));
        Rs5000Btn.setText("RS 5000");
        Rs5000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rs5000BtnMouseClicked(evt);
            }
        });

        Rs10000Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rs10000Btn.setForeground(new java.awt.Color(0, 51, 255));
        Rs10000Btn.setText("RS 10000");
        Rs10000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rs10000BtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("LOG OUT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("MAK Bank");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("BALANCE");

        BalanceTb.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Rs100Btn)
                                                        .addComponent(Rs5000Btn))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Rs500Btn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addGap(77, 77, 77))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(BalanceTb)
                                                .addGap(85, 85, 85)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Rs1000Btn)
                                        .addComponent(Rs10000Btn)
                                        .addComponent(Rs200Btn))
                                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Rs100Btn)
                                                        .addComponent(Rs200Btn))
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Rs500Btn)
                                                        .addComponent(Rs1000Btn)
                                                        .addComponent(jLabel5))
                                                .addGap(47, 47, 47)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Rs10000Btn)
                                                        .addComponent(Rs5000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(BalanceTb)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void Rs200BtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Rs500BtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Rs100BtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Rs100BtnMouseClicked(java.awt.event.MouseEvent evt) {
        if(getBalance()<100){
            JOptionPane.showMessageDialog(this,"LOW BALANCE");
        }
        else{
            try{
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
                Statement st = con.createStatement();
                int NewBalance = getBalance()-100;
                String q = "update accounttable set Balance='"+NewBalance+"' where AccNum='"+MyAccNum+"'";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(this,"UPDATED");
                con.close();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }

    private void Rs200BtnMouseClicked(java.awt.event.MouseEvent evt) {
        if(getBalance()<200){
            JOptionPane.showMessageDialog(this,"LOW BALANCE");
        }
        else{
            try{
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
                Statement st = con.createStatement();
                int NewBalance = getBalance()-200;
                String q = "update accounttable set Balance='"+NewBalance+"' where AccNum='"+MyAccNum+"'";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(this,"UPDATED");
                con.close();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }

    private void Rs500BtnMouseClicked(java.awt.event.MouseEvent evt) {
        if(getBalance()<500){
            JOptionPane.showMessageDialog(this,"LOW BALANCE");
        }
        else{
            try{
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
                Statement st = con.createStatement();
                int NewBalance = getBalance()-500;
                String q = "update accounttable set Balance='"+NewBalance+"' where AccNum='"+MyAccNum+"'";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(this,"UPDATED");
                con.close();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }

    private void Rs1000BtnMouseClicked(java.awt.event.MouseEvent evt) {
        if(getBalance()<1000){
            JOptionPane.showMessageDialog(this,"LOW BALANCE");
        }
        else{
            try{
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
                Statement st = con.createStatement();
                int NewBalance = getBalance()-1000;
                String q = "update accounttable set Balance='"+NewBalance+"' where AccNum='"+MyAccNum+"'";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(this,"UPDATED");
                con.close();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }

    private void Rs5000BtnMouseClicked(java.awt.event.MouseEvent evt) {
        if(getBalance()<5000){
            JOptionPane.showMessageDialog(this,"LOW BALANCE");
        }
        else{
            try{
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
                Statement st = con.createStatement();
                int NewBalance = getBalance()-5000;
                String q = "update accounttable set Balance='"+NewBalance+"' where AccNum='"+MyAccNum+"'";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(this,"UPDATED");
                con.close();

            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }

    private void Rs10000BtnMouseClicked(java.awt.event.MouseEvent evt) {
        if(getBalance()<10000){
            JOptionPane.showMessageDialog(this,"UPDATED");
        }
        else{
            try{
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_managment","root","1234");
                Statement st = con.createStatement();
                int NewBalance=getBalance()-10000;
                String q ="update accounttable set Balance='"+NewBalance+"' where AccNum='"+MyAccNum+"'";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(this, "UPDATED");
                con.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel BalanceTb;
    private javax.swing.JButton Rs10000Btn;
    private javax.swing.JButton Rs1000Btn;
    private javax.swing.JButton Rs100Btn;
    private javax.swing.JButton Rs200Btn;
    private javax.swing.JButton Rs5000Btn;
    private javax.swing.JButton Rs500Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration
}
